# Generated by Django 4.2.5 on 2023-09-23 10:44

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_type', models.CharField(choices=[('ZVIOO', 'Zastita vazduha i ozonskog omotaca'), ('ZVODE', 'Zastita vode'), ('ZZS', 'Zastita zivotne sredine'), ('ZBIV', 'Zastita od buke i vibracije'), ('ZZ', 'Zastita zemljista'), ('ZP', 'Zasticena podrucja'), ('ZVRSTE', 'Zasticene vrste'), ('RV', 'Ribolovne vode'), ('UO', 'Upravljanje otpadom'), ('HU', 'Hemijski udesi')], max_length=6)),
                ('city', models.CharField(choices=[('DO', 'Doboj'), ('BL', 'Banja Luka'), ('BJ', 'Bijeljina'), ('IS', 'Istocno Sarajevo')], max_length=2)),
                ('title', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('last_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
