# Generated by Django 4.2.5 on 2023-09-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportproblem',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
